version: '3.1'

services:

  friction_postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: friction
      POSTGRES_PASSWORD: Postgres!23
      POSTGRES_DB: friction
    ports:
      - "5432:5432"
